name: Test

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  test:
    name: Test ${{ matrix.package }} (Node ${{ matrix.node-version }})
    env:
      CI: true

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18, 19 ]
        package: ['koam', 'koam-router']
        include:
          - node-version: 18
            codecov: true

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
          run_install: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: pnpm --filter=${{ matrix.package }}... build

      - name: TypeScript check
        run: pnpm --filter=${{ matrix.package }} type-check

      - name: Eslint check
        run: pnpm --filter=${{ matrix.package }} exec eslint
        continue-on-error: true

      - name: Unit test
        run: pnpm --filter=${{ matrix.package }} test

      - name: Update coverage report
        if: ${{ matrix.codecov }}
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: ${{ matrix.package }}
